on:
  push:
    branches: develop
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: make s21_string.a
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test
  gcov_report:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: make gcov_report
  style:
    runs-on: macos-latest
    steps:
      - uses: action/checkout@v1
      - run: make style