on:
  push:
    branches: develop
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: make s21_string.a
  test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - run: brew install check
      - run: make test
  gcov_report:
    runs-on: macos-latest
    needs: [build, test]
    steps:
      - id: step1
        uses: actions/checkout@v1
      - id: step2
        run: brew install check
      - id: step3
        run: brew install gcovr
      - id: step4
        run: brew install lcov
      - id: step5
        run: bash gcov_script.sh
  style:
    runs-on: macos-latest
    needs: [build, test, gcov_report]
    steps:
      - uses: actions/checkout@v1
      - run: brew install clang-format
      - run: bash style.sh